export const ErrorCodes = {
  AUTH_MISSING_FIELDS: "AUTH_MISSING_FIELDS",
  AUTH_INVALID_USER: "AUTH_INVALID_USER",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ERROR_ONE: "ERROR_ONE",
  ADMIN_REGISTER_DUPLICATE: "ADMIN_REGISTER_DUPLICATE",
  QUESTION_INVALID_ID: "INVALID_QUESTION_ID",
  UNMATCH_WITH_QUESTIONTYPE: "UNMATCH_WITH_QUESTIONTYPE",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  DUPLICATE: "DUPLICATE",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
